name: Cerro Porteño
favicon: null
layout_spectrum: 0.04786208178848028
typography_spectrum: 0.4352788799442351
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7425669077783823
  lightness: 0.8053216168191284
  saturation: 0.6935113640502095
  rhythmicContrast: 0.4898138989228755
purpose: []
